### PR TITLE
35 rename registrant1 and registrant2 to from to in g2pregistrantrelationship

### LINKED ISSUE #35: rename `registrant1` and `registrant2` to `from` `to` in G2PRegistrantRelationship
- [ ] rename registrant1 and registrant2 to `from` `to` @emjay0921: do this ASAP
- [ ] Automatically generate the reverse relation and keep it updated with the other one: @jeremi will work on it.
- [ ] Update the UI @emjay0921

### PR DESCRIPTION
**Pull request by emjay0921**

### CODE REVIEW

**Review by jeremi — APPROVED** [review]

**Comment by jeremi** [comment]
@emjay0921 we need to prepare the update of all the other apps that are using this, like rest.

**Comment by emjay0921** [comment]
> @emjay0921 we need to prepare the update of all the other apps that are using this, like rest.

I have also updated this on the rest-api branch. And I checked also on other apps, even demo is not using the reg.rel, so far  only the apps in g2p_registry uses that.

**Review by jeremi — DISMISSED** [review]

**Comment by jeremi** [comment]
@emjay0921 can you fix the conflicts?

**Comment by emjay0921** [comment]
> @emjay0921 can you fix the conflicts?

Okay @jeremi , I'll do this now.

**Review by jeremi — DISMISSED** [review]

**Review by gonzalesedwin1123 — APPROVED** [review]

**Review by jeremi — APPROVED** [review]

**Pull request merged**
